name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    name: Frontend (Installing Dependencies + Testing)
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Frontend Tests
        run: |
          cd frontend
          npm test

  backend:
    runs-on: ubuntu-latest
    name: Backend (Installing Dependencies + Testing)
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Run Backend Tests
        run: |
          cd backend
          npm test

  gitleaks:
    runs-on: ubuntu-latest
    name: Run Gitleaks Scan
    needs: [frontend, backend]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Gitleaks
        uses: zricethezav/gitleaks-action@v1.0.0
        with:
          config: '.gitleaks.toml'
          leak-detection: true

  sonarqube:
    runs-on: ubuntu-latest
    name: Run SonarQube Scan and Quality Gate Check
    needs: [frontend, backend]  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SonarQube Scanner
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate Check
        run: |
          echo "Checking SonarQube Quality Gate Status..."
          QUALITY_GATE_STATUS=$(curl -s -u $SONAR_TOKEN: https://sonarcloud.io/api/qualitygates/project_status?projectKey=Deployment | jq -r '.projectStatus.status')

          if [[ "$QUALITY_GATE_STATUS" != "OK" ]]; then
            echo "SonarQube Quality Gate failed!"
            exit 1
          else
            echo "SonarQube Quality Gate passed."
          fi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
